import Header from "../Header";
const CyberSecurity = () => {
    const cybersecurityObjects = [
        {
          topic: 'Network Security',
          description: 'Focuses on protecting computer networks and infrastructure from unauthorized access or attacks.',
        },
        {
          topic: 'Firewall',
          description: 'A network security device that monitors and controls incoming and outgoing network traffic based on predetermined security rules.',
        },
        {
          topic: 'Malware Analysis',
          description: 'The process of studying and understanding malicious software to develop ways to detect and mitigate its impact.',
        },
        {
          topic: 'Encryption',
          description: 'The process of converting information into a code to prevent unauthorized access. Commonly used to protect data in transit and at rest.',
        },
        {
          topic: 'Penetration Testing',
          description: 'Ethical hacking technique where security experts simulate cyberattacks to identify vulnerabilities in a system or network.',
        },
        {
          topic: 'Incident Response',
          description: 'The process of responding to and managing the aftermath of a cybersecurity incident, including analysis, containment, eradication, and recovery.',
        },
        {
          topic: 'Two-Factor Authentication (2FA)',
          description: 'An extra layer of security that requires users to provide two different authentication factors (e.g., password and OTP) to verify their identity.',
        },
        {
          topic: 'Security Information and Event Management (SIEM)',
          description: 'A comprehensive solution that provides real-time analysis of security alerts generated by various hardware and software in a network.',
        },
        {
          topic: 'Phishing Awareness Training',
          description: 'Educational programs designed to teach individuals about the risks of phishing attacks and how to recognize and avoid them.',
        },
        {
          topic: 'Endpoint Security',
          description: 'Focuses on securing end-user devices (endpoints) such as computers, laptops, and mobile devices from security threats.',
        },
      ];
      
    return (
        <>
         <Header />
          <div className="container" style={{marginBottom:"3%"}}>
                <div className="row row-cols-1 row-cols-md-3 g-4">
                    {cybersecurityObjects.map((data, index) => (
                        <div className="col" key={index}>
                            <div className="card">
                                <img className="card-img-top" src="https://media.licdn.com/dms/image/D5612AQE0r5WC8r0HQg/article-cover_image-shrink_720_1280/0/1657711469335?e=2147483647&v=beta&t=y46kqfqImgi-IbshBGRs3lMz1HCTBvL8RjFAILShitg" alt="CardCap" />
                                <div className="card-body">
                                    <h5 className="card-title">{`${index + 1}. ${data.topic}`}</h5>
                                    <p className="card-text">{data.description}</p>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </>
    )
}

export default CyberSecurity;